In [1]:
def get_yelp_data_count(latitude, longitude, api_key, categories, radius=300, limit=50):
    url = 'https://api.yelp.com/v3/businesses/search'
    headers = {'Authorization': f'Bearer {api_key}'}
    params = {
        'latitude': latitude,
        'longitude': longitude,
        'radius': radius,
        'categories': categories,
        'limit': limit
    }
    response = requests.get(url, headers=headers, params=params)
    if response.status_code != 200:
        print(f"Error with Yelp API call: {response.status_code}")
        return 0
    else:
        return len(response.json()['businesses'])

In [3]:
import requests
import pandas as pd

In [4]:
import requests
import pandas as pd
import os
response = requests.get("http://api.citybik.es/v2/networks/citi-bike-nyc")
data = response.json()

bike_stations=data['network']['stations']
bike_stations
bike_stations=pd.json_normalize(bike_stations)
bike_station=bike_stations[['id', 'empty_slots', 'free_bikes', 'latitude', 'longitude']].copy()
bike_station

,id,empty_slots,free_bikes,latitude,longitude
0,46a983722ee1f51813a6a3eb6534a6e4,16,8,40.795000,-73.964500
1,81872dcff5f0e5f1e042aafcc0bab6fd,35,31,40.766741,-73.979069
2,fdb4831d3335a9aea380117ea4f4b81a,27,4,40.801694,-73.957145
3,678fea3bb3afe05788a35750358db726,7,12,40.795508,-73.941606
4,7ca4ed0b4fba2b2fb259ba84bd43e2ad,5,71,40.750585,-73.994685
...,...,...,...,...,...
2163,55bfc3325fe2553102257dbb4578054e,29,2,40.675832,-73.963308
2164,1a498b2ed244716550b887381fb54777,32,6,40.748036,-73.946705
2165,21b2048af20db72928025724c1b48bee,19,6,40.741130,-73.942518
2166,955c5f3727f4313d7c3fe28eb039f7b4,20,5,40.740288,-73.960697
2167,b7f0ddf33c64476f859253778189bc66,18,2,40.714420,-73.900970

In [7]:
API_KEY_YELP = 'h-3DVjg0SshNLUb3ICbRYw7aVUiFoYVtrEo7La9_HogC5KzgfmlaqM7PMD4dHlYjepR55pror7aMPvWfLlyGdbTn88CgTMtMDrgCQVY1x4_eRof8mkDwCWCpoDR9ZXYx'  # Replace with your actual Yelp API key

# Assuming you have a DataFrame named 'bike_station'
# bike_station = ...

# DataFrame to store the counts
yelp_data_counts = []

# Iterate over bike stations and fetch Yelp data for each category
for index, row in bike_station.head(5).iterrows():
    public_transport_count = get_yelp_data_count(row['latitude'], row['longitude'], API_KEY_YELP, 'Public Transportation')
    restaurant_count = get_yelp_data_count(row['latitude'], row['longitude'], API_KEY_YELP, 'Italian')
    active_life_count = get_yelp_data_count(row['latitude'], row['longitude'], API_KEY_YELP, 'Active Life')
    yelp_data_counts.append({
        'bike_station_id': row['id'],
        'public_transport_count': public_transport_count,
        'Chinese restaurant_count': restaurant_count,
        'active_life_count': active_life_count
    })

In [8]:
yelp_data_counts

[{'bike_station_id': '46a983722ee1f51813a6a3eb6534a6e4',
  'public_transport_count': 13,
  'Chinese restaurant_count': 13,
  'active_life_count': 13},
 {'bike_station_id': '81872dcff5f0e5f1e042aafcc0bab6fd',
  'public_transport_count': 50,
  'Chinese restaurant_count': 50,
  'active_life_count': 50},
 {'bike_station_id': 'fdb4831d3335a9aea380117ea4f4b81a',
  'public_transport_count': 31,
  'Chinese restaurant_count': 31,
  'active_life_count': 31},
 {'bike_station_id': '678fea3bb3afe05788a35750358db726',
  'public_transport_count': 50,
  'Chinese restaurant_count': 50,
  'active_life_count': 50},
 {'bike_station_id': '7ca4ed0b4fba2b2fb259ba84bd43e2ad',
  'public_transport_count': 50,
  'Chinese restaurant_count': 50,
  'active_life_count': 50}]